version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  install-node-example:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run: npm install
      - run: npm run build
workflows:
  test_my_app:
    jobs:
      - install-node-example
